version: '1.0'

services:
  db:
    image: postgres:14-alpine
    container_name: mini_blog_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mini_blog_development
    ports:
      - '5432:5432'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
    driver: local
