default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] || 'postgres' %>
  database: <%= ENV["POSTGRESQL_DATABASE"] || 'mini_blog_development' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] || 'postgres' %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 4 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5431 %>

development:
  <<: *default
  database: mini_blog_development

test:
  <<: *default
  database: mini_blog_test

production:
  <<: *default
  database: mini_blog_production
